/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import { PyasConnect as PyasConnectElement } from "@pyas/connect/dist/components/pyas-connect.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type PyasConnectEvents = {
    onAccountConnected: EventName<CustomEvent<{ provider: string; user: any }>>,
    onConnectError: EventName<CustomEvent<{ message: string, code: string | number | undefined }>>
};

export const PyasConnect: StencilReactComponent<PyasConnectElement, PyasConnectEvents> = /*@__PURE__*/ createComponent<PyasConnectElement, PyasConnectEvents>({
    tagName: 'pyas-connect',
    properties: {
        clientId: 'client-id',
        tokenName: 'token-name',
        showLabels: 'show-labels',
        theme: 'theme',
        autoOpen: 'auto-open',
        googleIcon: 'google-icon',
        outlookIcon: 'outlook-icon',
        zoomIcon: 'zoom-icon',
        icloudIcon: 'icloud-icon',
        modalTitle: 'modal-title',
        modalDescription: 'modal-description',
        formTitle: 'form-title',
        formDescription: 'form-description',
        showIcloud: 'show-icloud',
        showZoom: 'show-zoom',
        showGoogle: 'show-google',
        showOutlook: 'show-outlook',
        userName: 'user-name',
        userEmail: 'user-email',
        showDisclaimer: 'show-disclaimer',
        appName: 'app-name',
        state: 'state'
    },
    hydrateModule: import('@pyas/connect/hydrate'),
    serializeShadowRoot
});
