'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { PyasConnect as PyasConnectElement, defineCustomElement as definePyasConnect } from "@pyas/connect/dist/components/pyas-connect.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type PyasConnectEvents = {
    onAccountConnected: EventName<CustomEvent<{ provider: string; accountId: string, name: string, email: string, scopes: string[], status: string }>>,
    onConnectError: EventName<CustomEvent<{ message: string, code: string | number | undefined, error?: any }>>
};

export const PyasConnect: StencilReactComponent<PyasConnectElement, PyasConnectEvents> = /*@__PURE__*/ createComponent<PyasConnectElement, PyasConnectEvents>({
    tagName: 'pyas-connect',
    elementClass: PyasConnectElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onAccountConnected: 'accountConnected',
        onConnectError: 'connectError'
    } as PyasConnectEvents,
    defineCustomElement: definePyasConnect
});
